### ISSUE TITLE
How to use its app on last versions MacOS?

### ISSUE THREAD

**Issue by alexvoz** [Playrix/psd_ockham#1]
How to use its app on last versions MacOS?

**Comment by a-komarov-playrix** [comment]
What problem do you have?

**Comment by alexvoz** [comment]
Можно на русском?

Я скачиваю файл, открываю консоль, перехожу в эту папку, ввожу название файла, название psd файла - баш пишет, что не известная команда. или как правильно пользоваться. я вообще то видоусятник но надо дизам на маках объяснить как пользоваться утилитой

**Comment by alexvoz** [comment]
I download the file, open the console, cd to this folder, enter the name of the file, the name of the psd file - bash writes that command not found. Or how to use it correctly. I'm a windows user, but I need to explain how to use the utility on macos for designers.

**Comment by a-komarov-playrix** [comment]
I think the problem here that the utility doesn't have executable attribute. Open terminal, write `chmod +x `, then drag-n-drop psd_ockham to the terminal window (or type absolute path to the file). The command should look like this: `chmod +x /user/download/psd_ockham`. Hit Enter. After that you should be able to run the utility.
The solution doesn't depend on the version of MacOS.

**Comment by alexvoz** [comment]
Yes, chmod +x work. Thank you very much. Now I do - open terminal - drag-n-drop utility to terminal window, drag psd/psb file to terminal window, click to terminal window for focus and press enter. So, how use simplified method for this operation? Drag-drop psd file on utility don't work (like in Windows). Maybe you know how create sh script or context menu for psd/psb file or some like else?

**Comment by a-komarov-playrix** [comment]
Unfortunately, I don't know method simpler than drag-n-dropping files to the terminal. Drag-n-drop file on utility won't work, drag-n-drop file on .sh script won't work either.

**Comment by alexvoz** [comment]
Thank you for utility and help =)
